package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "zohotest2")
public class Activity implements java.io.Serializable {

	private int activityId;
	private Feeds feeds;
	private String activityName;
	private Date addeTime;
	private Set<Bug> bugs = new HashSet<Bug>(0);
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Milestone> milestones = new HashSet<Milestone>(0);

	public Activity() {
	}

	public Activity(int activityId) {
		this.activityId = activityId;
	}

	public Activity(int activityId, Feeds feeds, String activityName, Date addeTime, Set<Bug> bugs,
			Set<Project> projects, Set<Milestone> milestones) {
		this.activityId = activityId;
		this.feeds = feeds;
		this.activityName = activityName;
		this.addeTime = addeTime;
		this.bugs = bugs;
		this.projects = projects;
		this.milestones = milestones;
	}

	@Id

	@Column(name = "ActivityId", unique = true, nullable = false)
	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Feed_id")
	public Feeds getFeeds() {
		return this.feeds;
	}

	public void setFeeds(Feeds feeds) {
		this.feeds = feeds;
	}

	@Column(name = "ActivityName")
	public String getActivityName() {
		return this.activityName;
	}

	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AddeTime", length = 19)
	public Date getAddeTime() {
		return this.addeTime;
	}

	public void setAddeTime(Date addeTime) {
		this.addeTime = addeTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activity")
	public Set<Bug> getBugs() {
		return this.bugs;
	}

	public void setBugs(Set<Bug> bugs) {
		this.bugs = bugs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activity")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	

}
