package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bug generated by hbm2java
 */
@Entity
@Table(name = "bug", catalog = "zohotest2")
public class Bug implements java.io.Serializable {

	private int bugId;
	private Activity activity;
	private Project project;
	private String bugTitle;
	private Integer closed;
	private String descrption;
	private Date dueDate;
	private Integer open;

	public Bug() {
	}

	public Bug(int bugId) {
		this.bugId = bugId;
	}

	public Bug(int bugId, Activity activity, Project project, String bugTitle, Integer closed, String descrption,
			Date dueDate, Integer open) {
		this.bugId = bugId;
		this.activity = activity;
		this.project = project;
		this.bugTitle = bugTitle;
		this.closed = closed;
		this.descrption = descrption;
		this.dueDate = dueDate;
		this.open = open;
	}

	@Id

	@Column(name = "BugId", unique = true, nullable = false)
	public int getBugId() {
		return this.bugId;
	}

	public void setBugId(int bugId) {
		this.bugId = bugId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ActivityId")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectId")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "BugTitle")
	public String getBugTitle() {
		return this.bugTitle;
	}

	public void setBugTitle(String bugTitle) {
		this.bugTitle = bugTitle;
	}

	@Column(name = "Closed")
	public Integer getClosed() {
		return this.closed;
	}

	public void setClosed(Integer closed) {
		this.closed = closed;
	}

	@Column(name = "Descrption")
	public String getDescrption() {
		return this.descrption;
	}

	public void setDescrption(String descrption) {
		this.descrption = descrption;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DueDate", length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "Open")
	public Integer getOpen() {
		return this.open;
	}

	public void setOpen(Integer open) {
		this.open = open;
	}

}
