package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "zohotest2")
public class Client implements java.io.Serializable {

	private int clientId;
	private String clientName;
	private Set<User> users = new HashSet<User>(0);
	private Set<Project> projects = new HashSet<Project>(0);

	public Client() {
	}

	public Client(int clientId) {
		this.clientId = clientId;
	}

	public Client(int clientId, String clientName, Set<User> users, Set<Project> projects) {
		this.clientId = clientId;
		this.clientName = clientName;
		this.users = users;
		this.projects = projects;
	}

	@Id

	@Column(name = "ClientID", unique = true, nullable = false)
	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	@Column(name = "ClientName")
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
