package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Documents generated by hbm2java
 */
@Entity
@Table(name = "documents", catalog = "zohotest2")
public class Documents implements java.io.Serializable {

	private int docId;
	private String dcoName;
	private Set<Project> projects = new HashSet<Project>(0);

	public Documents() {
	}

	public Documents(int docId) {
		this.docId = docId;
	}

	public Documents(int docId, String dcoName, Set<Project> projects) {
		this.docId = docId;
		this.dcoName = dcoName;
		this.projects = projects;
	}

	@Id

	@Column(name = "DocID", unique = true, nullable = false)
	public int getDocId() {
		return this.docId;
	}

	public void setDocId(int docId) {
		this.docId = docId;
	}

	@Column(name = "DcoName")
	public String getDcoName() {
		return this.dcoName;
	}

	public void setDcoName(String dcoName) {
		this.dcoName = dcoName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documents")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
