package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "zohotest2")
public class Event implements java.io.Serializable {

	private int eventId;
	private String duartions;
	private String eventTitle;
	private String location;
	private Date scheduledDate;

	public Event() {
	}

	public Event(int eventId) {
		this.eventId = eventId;
	}

	public Event(int eventId, String duartions, String eventTitle, String location, Date scheduledDate) {
		this.eventId = eventId;
		this.duartions = duartions;
		this.eventTitle = eventTitle;
		this.location = location;
		this.scheduledDate = scheduledDate;
	}

	@Id

	@Column(name = "EventId", unique = true, nullable = false)
	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	@Column(name = "Duartions")
	public String getDuartions() {
		return this.duartions;
	}

	public void setDuartions(String duartions) {
		this.duartions = duartions;
	}

	@Column(name = "Event_Title")
	public String getEventTitle() {
		return this.eventTitle;
	}

	public void setEventTitle(String eventTitle) {
		this.eventTitle = eventTitle;
	}

	@Column(name = "Location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ScheduledDate", length = 19)
	public Date getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

}
