package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Projectgroup generated by hbm2java
 */
@Entity
@Table(name = "projectgroup", catalog = "zohotest2")
public class Projectgroup implements java.io.Serializable {

	private int projectGroupId;
	private Project project;
	private String groupName;

	public Projectgroup() {
	}

	public Projectgroup(int projectGroupId) {
		this.projectGroupId = projectGroupId;
	}

	public Projectgroup(int projectGroupId, Project project, String groupName) {
		this.projectGroupId = projectGroupId;
		this.project = project;
		this.groupName = groupName;
	}

	@Id

	@Column(name = "ProjectGroupId", unique = true, nullable = false)
	public int getProjectGroupId() {
		return this.projectGroupId;
	}

	public void setProjectGroupId(int projectGroupId) {
		this.projectGroupId = projectGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectId")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "GroupName")
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

}
