package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "zohotest2")
public class Project implements java.io.Serializable {

	private int projectId;
	private Client client;
	private Activity activity;
	private Documents documents;
	private String billingMethod;
	private Double bugdet;
	private Date endDate;
	private String overview;
	private String projectName;
	private Date startDate;
	private String statusActive;
	private Set<Bug> bugs = new HashSet<Bug>(0);
	private Set<Milestone> milestones = new HashSet<Milestone>(0);
	private Set<Projectgroup> projectgroups = new HashSet<Projectgroup>(0);
	private Set<ProjectManager> projectManagers = new HashSet<ProjectManager>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Status> statuses = new HashSet<Status>(0);

	public Project() {
	}

	public Project(int projectId) {
		this.projectId = projectId;
	}

	public Project(int projectId, Client client, Activity activity, Documents documents, String billingMethod,
			Double bugdet, Date endDate, String overview, String projectName, Date startDate, String statusActive,
			Set<Bug> bugs, Set<Milestone> milestones, Set<Projectgroup> projectgroups,
			Set<ProjectManager> projectManagers, Set<User> users, Set<Status> statuses) {
		this.projectId = projectId;
		this.client = client;
		this.activity = activity;
		this.documents = documents;
		this.billingMethod = billingMethod;
		this.bugdet = bugdet;
		this.endDate = endDate;
		this.overview = overview;
		this.projectName = projectName;
		this.startDate = startDate;
		this.statusActive = statusActive;
		this.bugs = bugs;
		this.milestones = milestones;
		this.projectgroups = projectgroups;
		this.projectManagers = projectManagers;
		this.users = users;
		this.statuses = statuses;
	}

	@Id

	@Column(name = "ProjectId", unique = true, nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ClientId")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ActivityId")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DocID")
	public Documents getDocuments() {
		return this.documents;
	}

	public void setDocuments(Documents documents) {
		this.documents = documents;
	}

	@Column(name = "BillingMethod")
	public String getBillingMethod() {
		return this.billingMethod;
	}

	public void setBillingMethod(String billingMethod) {
		this.billingMethod = billingMethod;
	}

	@Column(name = "Bugdet", precision = 22, scale = 0)
	public Double getBugdet() {
		return this.bugdet;
	}

	public void setBugdet(Double bugdet) {
		this.bugdet = bugdet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "Overview")
	public String getOverview() {
		return this.overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}

	@Column(name = "ProjectName")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "StatusActive")
	public String getStatusActive() {
		return this.statusActive;
	}

	public void setStatusActive(String statusActive) {
		this.statusActive = statusActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Bug> getBugs() {
		return this.bugs;
	}

	public void setBugs(Set<Bug> bugs) {
		this.bugs = bugs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Milestone> getMilestones() {
		return this.milestones;
	}

	public void setMilestones(Set<Milestone> milestones) {
		this.milestones = milestones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Projectgroup> getProjectgroups() {
		return this.projectgroups;
	}

	public void setProjectgroups(Set<Projectgroup> projectgroups) {
		this.projectgroups = projectgroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<ProjectManager> getProjectManagers() {
		return this.projectManagers;
	}

	public void setProjectManagers(Set<ProjectManager> projectManagers) {
		this.projectManagers = projectManagers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Status> getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set<Status> statuses) {
		this.statuses = statuses;
	}

}
