package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sharebug generated by hbm2java
 */
@Entity
@Table(name = "sharebug", catalog = "zohotest2")
public class Sharebug implements java.io.Serializable {

	private int shareBugId;
	private Date date;
	private String shareBugName;

	public Sharebug() {
	}

	public Sharebug(int shareBugId) {
		this.shareBugId = shareBugId;
	}

	public Sharebug(int shareBugId, Date date, String shareBugName) {
		this.shareBugId = shareBugId;
		this.date = date;
		this.shareBugName = shareBugName;
	}

	@Id

	@Column(name = "ShareBugId", unique = true, nullable = false)
	public int getShareBugId() {
		return this.shareBugId;
	}

	public void setShareBugId(int shareBugId) {
		this.shareBugId = shareBugId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "ShareBugName")
	public String getShareBugName() {
		return this.shareBugName;
	}

	public void setShareBugName(String shareBugName) {
		this.shareBugName = shareBugName;
	}

}
