package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "zohotest2")
public class Status implements java.io.Serializable {

	private int statsuId;
	private Feeds feeds;
	private Project project;
	private String statusCompletedPercent;

	public Status() {
	}

	public Status(int statsuId) {
		this.statsuId = statsuId;
	}

	public Status(int statsuId, Feeds feeds, Project project, String statusCompletedPercent) {
		this.statsuId = statsuId;
		this.feeds = feeds;
		this.project = project;
		this.statusCompletedPercent = statusCompletedPercent;
	}

	@Id

	@Column(name = "StatsuId", unique = true, nullable = false)
	public int getStatsuId() {
		return this.statsuId;
	}

	public void setStatsuId(int statsuId) {
		this.statsuId = statsuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Feed_id")
	public Feeds getFeeds() {
		return this.feeds;
	}

	public void setFeeds(Feeds feeds) {
		this.feeds = feeds;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectId")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "StatusCompletedPercent")
	public String getStatusCompletedPercent() {
		return this.statusCompletedPercent;
	}

	public void setStatusCompletedPercent(String statusCompletedPercent) {
		this.statusCompletedPercent = statusCompletedPercent;
	}

}
