package in.com.prestige.dto;
// Generated May 30, 2018 4:58:22 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "zohotest2")
public class User implements java.io.Serializable {

	private int userId;
	private Client client;
	private Milestone milestone;
	private Project project;
	private String email;
	private String role;
	private String userName;
	private Set<Feeds> feedses = new HashSet<Feeds>(0);

	public User() {
	}

	public User(int userId) {
		this.userId = userId;
	}

	public User(int userId, Client client, Milestone milestone, Project project, String email, String role,
			String userName, Set<Feeds> feedses) {
		this.userId = userId;
		this.client = client;
		this.milestone = milestone;
		this.project = project;
		this.email = email;
		this.role = role;
		this.userName = userName;
		this.feedses = feedses;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ClientId")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MilestoneId")
	public Milestone getMilestone() {
		return this.milestone;
	}

	public void setMilestone(Milestone milestone) {
		this.milestone = milestone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectId")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Role")
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "UserName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Feeds> getFeedses() {
		return this.feedses;
	}

	public void setFeedses(Set<Feeds> feedses) {
		this.feedses = feedses;
	}

}
